classdef MixBernoulli < MixDiscrete
    methods
        function model = MixBernoulli(varargin)
            args = processArgs(varargin                              ,...
                '-nmixtures'    , 2                                  ,...
                '-template'     , BernoulliDist([0.5;0.5])           ,...
                '-mixingDist'   , []                                 ,...
                '-mixtureComps' , {}                                 ,...
                '-fitEng'       , MixDiscreteEmFitEng() );
            model = model@MixDiscrete(args{:}); 
        end
    end
end