classdef MixDiscrete < MixtureModel
% Mixture of Discrete Distributions.
	methods
		function model = MixDiscrete(varargin)
        % sets defaults specific to the model    
            args = processArgs(varargin                              ,...
                '-nmixtures'    , 2                                  ,...
                '-template'     , DiscreteDist(normalize(rand(2,1))) ,...
                '-mixingDist'   , []                                 ,...
                '-mixtureComps' , {}                                 ,...
                '-fitEng'       , MixDiscreteEmFitEng() );
            model = model@MixtureModel(args{:});
        end
    end
end