classdef MixMvn < MixtureModel
% Mixture of Multivariate Normal Distributions    
	methods
		function model = MixMvn(varargin)
        % sets defaults specific to the model    
            args = processArgs(varargin                         ,...
                '-nmixtures'    , 2                             ,...
                '-template'     , MvnDist(randn(1,2),randpd(2)) ,...
                '-mixingDist'   , []                            ,...
                '-mixtureComps' , {}                            ,...
                '-fitEng'       , MixMvnEmFitEng() );
            model = model@MixtureModel(args{:});
        end
    end
end